language: cpp
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages:
      - gcc-6
      - g++-6
      - clang-5.0
      - clang++-5.0

matrix:
  include:
    - os: linux
      compiler: gcc
      env: CC=gcc-6 CXX=g++-6
    - os: linux
      compiler: clang
      env: CC=clang-5.0 CXX=clang++-5.0

before_install:
  - wget -c https://github.com/adamcavendish/ReasonableCMakeForCXX/releases/download/cmake-3.7.2/cmake-3.7_3.7.2.amd64.deb
  - sudo dpkg -i cmake-3.7_3.7.2.amd64.deb
  - cmake --version
  - git clone --depth 1 https://github.com/glfw/glfw.git
  - cd glfw3
  - mkdir build/
  - cmake ..
  - make -j$(nproc)
  - sudo make install

script:
  - bash ./build.bash
